### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by lewtds** [Openroadvietnam/openaccounting#1]
Mình thấy project hiện tại hoàn toàn không có test, rất nguy hiểm với production code. Trước mắt không nhất thiết phải test mọi thứ nhưng những đoạn logic trong kế toán ít phải đụng đến bên ngoài thì hoàn toàn có thể test được.

Về unit test framework thì có thể dùng [mocha](http://mochajs.org/) hoặc [node-unit](https://github.com/caolan/nodeunit).

**Comment by pvtruong** [comment]
Thank you anh đã góp ý. Em sẽ bổ xung unit test

**Comment by tuanta** [comment]
Trong cộng đồng khi chưa được gặp nhau cứ dùng nhân xưng anh và tôi là OK.
Btw, Trung là đội 9x, nhỏ tuổi hơn Trường :D
